
name: Deploy to InfinityFree

on:
  push:
    branches: [ "main" ] # Se déclenche quand vous poussez sur la branche 'main'
  workflow_dispatch: # Permet un déclenchement manuel depuis l'onglet Actions

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v4

      - name: Prepare config.php with secrets
        run: |
          cp config/config.example.php config/config.php
          sed -i "s|your_db_name_here|${{ secrets.DB_NAME }}|g" config/config.php
          sed -i "s|your_username_here|${{ secrets.DB_USER }}|g" config/config.php
          sed -i "s|your_password_here|${{ secrets.DB_PASS }}|g" config/config.php
          sed -i "s|localhost|${{ secrets.DB_HOST }}|g" config/config.php

      - name: Sync files to InfinityFree and 
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftpupload.net # Serveur FTP d'InfinityFree
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /htdocs/ # Dossier où déposer les fichiers
